prefixstyle: '&7[%s] '

maxsize: 10
playerfile: 'players.json'

lang:
  error:
    lazy: '&cI don''t want to implement it, but if you find this @ me in the Discord.'
    usage: '&cUsage: %s'
    noplayer: '&cPlayer not found.'
    outgoing: '&cYou already have an outgoing request.'

  permission:
    leader: '&cYou have to be the leader of a faction to do this.'
    cantkick: '&cYou can''t kick %s, they are not in your faction.'

  faction:
    info:
      - '&8&m------------------'
      - '&7Name: &5%s &7(%s)'
      - '&7Members: &d%,d&7/%,d'
      - '&r'
      - '%s'
      - '&8&m------------------'

    error:
      full: '&cYou already have the maximum amount of people in the faction.'
      leaderoff: '&cYou cannot request to join right now, the leader is offline.'
      nojoin: '&cYou cannot join a faction, you''re in one.'
      noexisting: '&cFaction with the name ''%s'' does not exist.'
      nofaction: '&cYou are not in a faction right now.'
      cantleave: '&cYou cannot leave the faction when you''re the leader. If you want this changed please talk to the admins.'
      kickself: '&cYou can''t kick yourself, sorry, nice try to escape.'

    broadcast:
      chat: '&5%s > &e%s&f: %s'
      playerkicked: '&c%s has kicked %s from the faction.'
      playerquit: '&c%s has quit the faction.'

    chat:
      focustoggle: '&aNow speaking in &6%s&a, use this command again to toggle it.'
      off: '&cYou can''t talk in faction chat while it''s off for you. Do /f chat to re-enable.'
      toggle: '&aToggled the faction chat &6%s&a.'

    kicked: '&cYou''ve been kicked from the faction.'
    left: '&aYou have successfully left %s, farewell!'

    join:
      joined: '&a%s accepted %s into the faction.'
      expired: '&cYour request to join has expired.'
      leaderoff: '&cYou cannot request to join %s at the time, the leader is offline. If you are a part of this faction please wait until they are online or tell them to login.'
      requested: '&aYour join request has been sent to %s, wait for the leader to accept.'
      request: '&a%s has requested to join the faction. You have 30 seconds to use &6/f accept %1$s &ato let them in.'

  configreload: '&aReloaded the factions config.'


factions:
  cc:
    leader: 'e17608a4-2f5c-4f53-83f4-93f23835cc5d'
    name: 'Crimson Cult'
    max: 0
  aa:
    leader: '06153fd2-9a4d-4e79-8557-47eda26e1f78'
    name: 'Arcane Acolytes'
    max: 0
  sc:
    leader: 'f88e7580-09bf-4a75-8306-f7f19811fcf9'
    name: 'Steel Convenant'
    max: 0
  how:
    leader: 'ef6e5448-361f-4724-ae15-1210c150f5bb'
    name: 'Hunters of Wildverne'
    max: 0
  lxe:
    leader: 'ef6e5448-361f-4724-ae15-1210c150f5bb'
    name: 'Lord''s of Excalibur''s Edge'
    max: 0
